version: '3'
services:
  frontend:
    build: frontend/
    ports:
      - "3000:80"
    links:
      - backend
      - redis

  backend:
    build: backend/
    ports:
      - "5000:5000"
    links:
      - redis
    environment:
      - redis_host=redis
      - redis_port=6379
      - redis_password=
      - consumer_key=
      - consumer_secret=
      - access_token=
      - access_token_secret=

  redis:
    image: redis:6.0.3
    restart: always